# Generated by Django 3.2.18 on 2023-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familya', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('tg_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ism', models.IntegerField(max_length=30, unique=True)),
            ],
        ),
    ]
